### ISSUE TITLE
formalization

### ISSUE THREAD

**Issue by susl16c** [mistermantas/millionaire-js#4]
If he would still betray a good design he would not have the price

**Comment by mistermantas** [comment]
What?  I don't understand

**Comment by susl16c** [comment]
Here in this way you can not create one design and functionality?
https://lukewlodarczyk.github.io/Who-Wants-to-Be-a-Millionaire/#/

**Comment by mistermantas** [comment]
Your English is really bad. Just say what you want in Russian

**Comment by susl16c** [comment]
я увидел классное приложение (https://lukewlodarczyk.github.io/Who-Wants-to-Be-a-Millionaire/#/) и хотел его интегрировать на форум, но не могу так как оно использует вопросы по API, а я хотел чтобы были они локально, потому что у меня другой язык и спрашиваю вас можете вы оформить свое приложение так как я указан в ссылке ?

**Comment by mistermantas** [comment]
No. I made this for school, not entertainment.

Нет. Я сделал это для школы, а не для развлечения.
